name: Step 0 # Start Exercise

on:
  # Auto-start lorsque l'élève crée un dépôt depuis la template
  push:
    branches: [ main ]
  # En complément, si la branche par défaut est créée sans commit
  create:
  # Garde le déclencheur manuel en secours
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write # si tu veux commenter sur les PR
  actions: write    # si tu utilises gh workflow enable/disable
env:
  STEP_1_FILE: ".github/steps/1-step.md"

jobs:
  start_exercise:
    if: |
      !github.event.repository.is_template
    name: Start Exercise
    uses: skills/exercise-toolkit/.github/workflows/start-exercise.yml@v0.7.1
    with:
      exercise-title: "GitHub Basics"
      intro-message: "Bienvenue ! Cette issue va te guider pas à pas dans le cours."

  post_next_step_content:
    name: Post next step content
    runs-on: ubuntu-latest
    needs: [start_exercise]
    env:
      ISSUE_NUMBER: ${{ needs.start_exercise.outputs.issue-number }}
      ISSUE_REPOSITORY: ${{ github.repository }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Remplacer le corps de l’issue par la version FR
        uses: actions/github-script@v7
        env:
          ISSUE_NUMBER: ${{ env.ISSUE_NUMBER }}
        with:
          script: |
            const {owner, repo} = context.repo;
            const number = process.env.ISSUE_NUMBER;
            const body = [
              "👋 Salut @" + context.actor + " ! Bienvenue dans ton exercice **GitHub Skills**.",
              "",
              "Bienvenue, cette issue va te guider pas à pas dans le cours.",
              "",
              "✨ Il s'agit d'un exercice GitHub Skills interactif et pratique.",
              "",
              "Au fil des étapes, je publierai des mises à jour dans les commentaires :",
              "",
              "✅ Vérifier ton travail et t’indiquer la suite  ",
              "💡 Partager des conseils et des ressources  ",
              "🚀 Célébrer ta progression et la fin",
              "",
              "C'est parti, amuse-toi bien !",
              "",
              "Mona"
            ].join('\n');
            await github.rest.issues.update({ owner, repo, issue_number: Number(number), body });

      - name: Create comment - add step content
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: ${{ env.STEP_1_FILE }}
          vars: |
            login: ${{ github.actor }}
            full_repo_name: ${{ github.repository }}

      - name: Create comment - watching for progress
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: .github/i18n/fr/watching-for-progress.md

      - name: Enable next step workflow
        run: gh workflow enable "Step 1"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}