name: Step 1

on:
  # Se déclenche quand l'élève crée la branche de l’exercice
  create:
  # Si la branche est créée par un premier push
  push:
    branches: [ my-first-branch ]
  workflow_dispatch:

permissions:
  contents: read
  actions: write
  issues: write
  pull-requests: write

env:
  STEP_2_FILE: ".github/steps/2-step.md"

jobs:
  find_exercise:
    name: Find Exercise Issue
    if: >
      (github.event_name == 'create' && github.event.ref_type == 'branch' && github.event.ref == 'my-first-branch')
      || (github.event_name == 'push' && endsWith(github.ref, '/my-first-branch'))
    uses: skills/exercise-toolkit/.github/workflows/find-exercise-issue.yml@v0.7.1

  post_next_step_content:
    name: Post next step content
    needs: [find_exercise]
    if: >
      (github.event_name == 'create' && github.event.ref_type == 'branch' && github.event.ref == 'my-first-branch')
      || (github.event_name == 'push' && endsWith(github.ref, '/my-first-branch'))
    runs-on: ubuntu-latest
    env:
      ISSUE_REPOSITORY: ${{ github.repository }}
      ISSUE_NUMBER: ${{ needs.find_exercise.outputs.issue-number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create comment - step finished
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: .github/i18n/fr/step-finished-prepare-next-step.md
          vars: |
            next_step_number: 2

      - name: Create comment - add step content
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: ${{ env.STEP_2_FILE }}

      - name: Create comment - watching for progress
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: .github/i18n/fr/watching-for-progress.md

      - name: Disable current workflow and enable next one
        run: |
          gh workflow disable "${{ github.workflow }}"
          gh workflow enable "Step 2"
        env:
          GH_TOKEN: ${{ github.token }}
